apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: osac
  title: osac
  description: Open Sovereign AI Cloud (or whatever it will be called) hands-on lab
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: wkulhanek
    ph.rhdp.io/owner: wkulhane@redhat.com
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/osac
    ph.rhdp.io/created-at: 2026-08-18T08:09:08.412Z
  tags:
    - publishing-house
    - lab
    - rhdp-published
  links:
    - url: https://github.com/rhpds/osac
      title: Repository
      icon: github
    - url: https://devspaces.apps.ocpv-infra02.wdc07.infra.demo.redhat.com#https://github.com/rhpds/osac
      title: Open in DevSpaces
      icon: catalog
    - url: https://central-api-publishing-house.apps.ocpv-infra02.wdc07.infra.demo.redhat.com
      title: Central
      icon: dashboard
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
