site_name: 'OpenShift Cloud Extensions: Tenant Administration and VM Lifecycle'
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Osac Orientation: modules/module-01-osac-orientation.md
  - Module 2 - Tenant Administration: modules/module-02-tenant-administration.md
  - Module 3 - Vm Templates: modules/module-03-vm-templates.md
  - Module 4 - Virtual Networking: modules/module-04-virtual-networking.md
  - Module 5 - Vm Lifecycle: modules/module-05-vm-lifecycle.md
plugins:
- techdocs-core
